In [ ]:
def createFolder(directory):
    try:
        if not os.path.exists(directory):
            os.makedirs(directory)
    except OSError:
        print ('Error: Creating directory. ' +  directory)


In [ ]:
#path ='/content/drive/MyDrive/IU'
import os
import cv2
import numpy as np
from matplotlib import pyplot as plt
from PIL import Image
%matplotlib inline

root_dir = '/content/drive/MyDrive/BP'

possible_img_extension =['.jpg','.jpeg','.JPG','.png','.bmp']

face_cascade = cv2.CascadeClassifier('/content/drive/MyDrive/haarcascade_frontalface_default.xml')


for(root, dirs, files) in os.walk(root_dir):
  if len(files) > 0:
    for file_name in files:
            if os.path.splitext(file_name)[1] in possible_img_extension:
                current_dir =root[len(root_dir)+1:]#디렉토리
                current_uuid =file_name[:file_name.find('-original')]#uuid
                print('/content/drive/MyDrive/newpic/%s'%current_dir)
                createFolder('/content/drive/MyDrive/newpic/%s'%current_dir)
                img_path = root + '/' + file_name
                
                img_path = img_path.replace('\\', '/') # \는 \\로 나타내야함         
                image = cv2.imread(img_path, cv2.IMREAD_COLOR)
                
                grayImage = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
                faces = face_cascade.detectMultiScale(grayImage, 1.03, 5)
                print(faces)

                if(len(faces) ==1):
                  for (x,y,w,h) in faces:
                      newY = y-(h//3)
                      newYH = y+h+(h//3)
                      newX = x-(h//3)
                      newXH = x+h+(h//3)
                      if(newY <0):
                        newY =0
                      if(newX<0):
                        newX =0

                      cutting_img=image[newY:newYH, newX:newXH]
                  count += 1
                  plt.figure(figsize=(12,12))
                  image = cv2.cvtColor(cutting_img, cv2.COLOR_BGR2RGB)
                  # plt.imshow(image)
                  plt.imsave('/content/drive/MyDrive/newpic/%s/%s-sqaure.jpg'%(current_dir,current_uuid),image)

                  # plt.xticks([]), plt.yticks([])
                  # plt.show()
  print(count)


66
66
/content/drive/MyDrive/newpic/송혜교
[[ 43  74 196 196]
 [328  68 195 195]
 [ 87 229 119 119]]
/content/drive/MyDrive/newpic/송혜교
[[595  71  66  66]
 [822  70 149 149]
 [ 30  78 138 138]
 [315  74 168 168]]
/content/drive/MyDrive/newpic/송혜교
[[ 87 101 232 232]]
/content/drive/MyDrive/newpic/송혜교
[[476  95  30  30]
 [375  49  60  60]
 [425 132 108 108]
 [211  69 135 135]]
/content/drive/MyDrive/newpic/송혜교
[[282  44 276 276]]
/content/drive/MyDrive/newpic/송혜교
[[ 70 114 233 233]]
/content/drive/MyDrive/newpic/송혜교
[[ 32 143 311 311]]
/content/drive/MyDrive/newpic/송혜교
[[151  26 165 165]]
/content/drive/MyDrive/newpic/송혜교
[[131 161  78  78]
 [173 154 116 116]
 [220 246  62  62]]
/content/drive/MyDrive/newpic/송혜교
[[152 158 266 266]
 [423 140 111 111]]
/content/drive/MyDrive/newpic/송혜교
[[207  57 140 140]]
/content/drive/MyDrive/newpic/송혜교
[[239  83 169 169]
 [269 291 147 147]]
/content/drive/MyDrive/newpic/송혜교
[[462  54  76  76]
 [166 273  42

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:46: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).


[[132  56 130 130]
 [ 44 210 186 186]]
/content/drive/MyDrive/newpic/김혜수
[[206 109 221 221]
 [143 180  32  32]]
/content/drive/MyDrive/newpic/김혜수
[[120  84 308 308]
 [344 388 132 132]]
/content/drive/MyDrive/newpic/김혜수
[[ 63 151  88  88]]
/content/drive/MyDrive/newpic/김혜수
[[220  88 144 144]
 [288 294  57  57]]
/content/drive/MyDrive/newpic/김혜수
[[228 103 157 157]
 [429 145 164 164]
 [182 112 148 148]
 [253 228 117 117]
 [ 79 573  83  83]
 [407 662  60  60]]
/content/drive/MyDrive/newpic/김혜수
[[433  79  62  62]
 [186  61 126 126]
 [449 318  73  73]]
/content/drive/MyDrive/newpic/김혜수
[[ 98  68 112 112]
 [283 329  62  62]]
88
/content/drive/MyDrive/newpic/아이유
[[ 19  29 146 146]]
/content/drive/MyDrive/newpic/아이유
[[ 85 147 172 172]
 [232 240  59  59]
 [244 344 130 130]]
/content/drive/MyDrive/newpic/아이유
[[69 37 82 82]]
/content/drive/MyDrive/newpic/아이유
[[62 18 98 98]]
/content/drive/MyDrive/newpic/아이유
[[84 50 70 70]]
/content/drive/MyDrive/newpic/아

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>

<Figure size 864x864 with 0 Axes>